[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[dev]
  command = "python web_app.py"
  targetPort = 5001
  port = 8888

[[redirects]]
  from = "/*"
  to = "http://localhost:5001/:splat"
  status = 200
  force = true

